---

- name: Creates directory
  file: path={{item}} state=directory  mode=0775 owner=ctgmq group=ctgmq
  with_items:
    - /home/ctgmq/logs

- name: stop nameserver
  command: "sh /home/ctgmq/ctgmq-rocketmq/bin/mqshutdown namesrv"
  ignore_errors: true

- name: sart nameserver
  shell: "nohup sh /home/ctgmq/ctgmq-rocketmq/bin/mqnamesrv > /home/ctgmq/logs/mqnamesrv.out 2>&1 &"
  become: yes
  become_user: ctgmq
  poll: 0
  environment:
    JAVA_HOME: "/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64/jre/"